// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuG9MXFdSHTIbLNhyeEbSX_qa7gE-R9a0',
    appId: '1:363015084386:web:9163724c2e592a4150743b',
    messagingSenderId: '363015084386',
    projectId: 'e-commerce-7985c',
    authDomain: 'e-commerce-7985c.firebaseapp.com',
    storageBucket: 'e-commerce-7985c.firebasestorage.app',
    measurementId: 'G-8VD55B87CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeaUK0VuUpcwvxMo7T2g9bQAWNc-bGWwA',
    appId: '1:363015084386:android:facfa916a0c8af8950743b',
    messagingSenderId: '363015084386',
    projectId: 'e-commerce-7985c',
    storageBucket: 'e-commerce-7985c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttrqGcWDcTTJuiBVyTe2LmoU2k3aFtQc',
    appId: '1:363015084386:ios:a83c0c890a002e2c50743b',
    messagingSenderId: '363015084386',
    projectId: 'e-commerce-7985c',
    storageBucket: 'e-commerce-7985c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttrqGcWDcTTJuiBVyTe2LmoU2k3aFtQc',
    appId: '1:363015084386:ios:a83c0c890a002e2c50743b',
    messagingSenderId: '363015084386',
    projectId: 'e-commerce-7985c',
    storageBucket: 'e-commerce-7985c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuG9MXFdSHTIbLNhyeEbSX_qa7gE-R9a0',
    appId: '1:363015084386:web:31094c6162ccb33250743b',
    messagingSenderId: '363015084386',
    projectId: 'e-commerce-7985c',
    authDomain: 'e-commerce-7985c.firebaseapp.com',
    storageBucket: 'e-commerce-7985c.firebasestorage.app',
    measurementId: 'G-EL21NW8PJC',
  );
}
